"""Validate visible section content from the authoritative rendered parse."""
import re
from unicodedata import category

if __package__:
    from .pr_body import _has_visible_text
else:
    from pr_body import _has_visible_text

_LABEL = r'[^\s(),](?:[^(),\r\n]*[^\s(),])?'
_MODEL = rf'{_LABEL} \({_LABEL}(?:, {_LABEL})*\)'
_FOOTER = re.compile(rf'Generated by {_MODEL}(?:, {_MODEL})*')
_ATTRIBUTION = re.compile(r'([^(),]+) \(([^()]+)\)(?:, |$)')
_BUG = re.compile(r'#([1-9][0-9]{0,18}) (\S(?:.*\S)?)')
_INLINE = frozenset(('a', 'em', 'strong', 'code', 'span', 'del', 'b', 'i', 'u', 's'))
FOOTER_ERROR = (
    'Footer must contain exactly one final visible line: '
    '`Generated by <model> (<role>, <role>, ...), <model> (<role>, ...)`.')
BUGS_ERROR = (
    'Bugs Discovered must contain only unordered list items of the form '
    '`#N Literal issue title`, naming existing issues with their exact titles.')


def _visible(text):
    return re.sub(r'[ \t\r\n\f]+', ' ', text).strip(' ')


def _footer_line(content):
    parts = []
    for kind, value in content:
        if kind == 'text':
            parts.append(value)
        elif value in ('p', 'div', 'br'):
            parts.append('\n')
        elif value not in _INLINE:
            return None
    lines = [_visible(line) for line in ''.join(parts).splitlines()]
    lines = [line for line in lines if line]
    return lines[0] if len(lines) == 1 else None


def _bug_items(content):
    stack = []
    items = []
    parts = []
    paragraphs = 0
    for kind, value in content:
        if kind == 'text':
            if 'li' in stack:
                parts.append(value)
            elif value.strip():
                return None
        elif kind == 'start':
            if value == 'ul' and not stack:
                pass
            elif value == 'li' and stack == ['ul']:
                parts = []
                paragraphs = 0
            elif value == 'p' and stack == ['ul', 'li'] and paragraphs == 0:
                paragraphs += 1
            elif value in _INLINE and 'li' in stack:
                pass
            else:
                return None
            stack.append(value)
        else:
            if not stack or stack.pop() != value:
                return None
            if value == 'li':
                items.append(_visible(''.join(parts)))
    return items if not stack and items else None


def section_content(sections):
    """Return content errors and visible (issue number, title) bug pointers."""
    errors = []
    pointers = []
    for index, section in enumerate(sections):
        if section.key == 'footer':
            value = _footer_line(section.content)
            if (value is None or _FOOTER.fullmatch(value) is None
                    or index != len(sections) - 1
                    or any(category(char).startswith('C') for char in value)
                    or not all(_has_visible_text(label)
                               for model, roles in _ATTRIBUTION.findall(
                                   value.removeprefix('Generated by '))
                               for label in (model, *roles.split(', ')))):
                errors.append(FOOTER_ERROR)
        elif section.key == 'bugs discovered':
            items = _bug_items(section.content)
            matches = [_BUG.fullmatch(item) for item in (items or [])]
            if not matches or any(match is None for match in matches):
                errors.append(BUGS_ERROR)
            else:
                pointers.extend((int(match[1]), match[2]) for match in matches)
    return errors, pointers


def bug_issue_errors(pointers, records):
    errors = []
    for number, title in pointers:
        if number not in records:
            continue
        issue = records[number]
        if (issue is None or 'pull_request' in issue
                or issue.get('title') != title):
            errors.append(
                f'Bugs Discovered pointer `#{number}` must name an existing '
                'issue in this repository and copy its visible title exactly.')
    return errors
