"""Validate visible section content from the authoritative rendered parse."""
import re
from unicodedata import category

if __package__:
    from .pr_body import _has_visible_text
else:
    from pr_body import _has_visible_text

_LABEL = r'[^\s(),](?:[^(),\r\n]*[^\s(),])?'
_MODEL = rf'{_LABEL} \({_LABEL}(?:, {_LABEL})*\)'
_FOOTER = re.compile(rf'Generated by {_MODEL}(?:, {_MODEL})*')
_ATTRIBUTION = re.compile(r'([^(),]+) \(([^()]+)\)(?:, |$)')
_BUG = re.compile(r'#([1-9][0-9]{0,18}) (\S(?:.*\S)?)')
_INLINE = frozenset(('a', 'em', 'strong', 'code', 'span', 'del', 'b', 'i', 'u', 's'))
_CONTAINERS = frozenset(('div', 'span', 'section', 'article', 'main'))
_COLLAPSIBLE_WHITESPACE = re.compile(r'[ \t\r\n\f]+')
FOOTER_ERROR = (
    'Footer must contain exactly one final visible line: '
    '`Generated by <model> (<role>, <role>, ...), <model> (<role>, ...)`.')
BUGS_ERROR = (
    'Bugs Discovered must contain only unordered list items of the form '
    '`#N Literal issue title`, naming existing issues with their exact titles.')


def _append_text(runs, text, preserve):
    if runs and runs[-1][0] == preserve:
        runs[-1][1].append(text)
    else:
        runs.append((preserve, [text]))


def _visible_runs(runs):
    if not runs:
        return ''
    pieces = [''.join(text) if preserve else _COLLAPSIBLE_WHITESPACE.sub(' ', ''.join(text))
              for preserve, text in runs]
    # Normal-flow spaces at block edges disappear; code's break-spaces does
    # not discard them or turn preserved separators into different characters.
    if not runs[0][0]:
        pieces[0] = pieces[0].lstrip(' ')
    if not runs[-1][0]:
        pieces[-1] = pieces[-1].rstrip(' ')
    return ''.join(pieces)


def _footer_line(content):
    parts = [[]]
    code_depth = 0
    for kind, value in content:
        if kind == 'text':
            _append_text(parts[-1], value, code_depth > 0)
        elif value == 'code':
            code_depth += 1 if kind == 'start' else -1
        elif value in ('p', 'div', 'br'):
            parts.append([])
        elif value not in _INLINE:
            return None
    # Normal text collapses, code text preserves, and structural breaks stay
    # separate from both. All context comes from the existing rendered tokens.
    lines = [_visible_runs(part) for part in parts]
    lines = [line for line in lines if line]
    return lines[0] if len(lines) == 1 and len(lines[0].splitlines()) == 1 else None


def _bug_items(content):
    stack = []
    wrappers = 0
    items = []
    parts = []
    paragraphs = 0
    for kind, value in content:
        if kind == 'text':
            if 'li' in stack:
                _append_text(parts, value, 'code' in stack)
            elif value.strip():
                return None
        elif kind == 'start':
            # Grouping containers are transparent only around the list. Keep
            # their boundaries so text outside its items still fails validation.
            if value in _CONTAINERS and len(stack) == wrappers:
                wrappers += 1
            elif value == 'ul' and len(stack) == wrappers:
                pass
            elif value == 'li' and stack[wrappers:] == ['ul']:
                parts = []
                paragraphs = 0
            elif value == 'p' and stack[wrappers:] == ['ul', 'li'] and paragraphs == 0:
                paragraphs += 1
            elif value in _INLINE and 'li' in stack:
                pass
            else:
                return None
            stack.append(value)
        else:
            if not stack or stack.pop() != value:
                return None
            if len(stack) < wrappers:
                wrappers -= 1
            if value == 'li':
                items.append(_visible_runs(parts))
    return items if not stack and items else None


def section_content(sections):
    """Return content errors and visible (issue number, title) bug pointers."""
    errors = []
    pointers = []
    for index, section in enumerate(sections):
        if section.key == 'footer':
            value = _footer_line(section.content)
            if (value is None or _FOOTER.fullmatch(value) is None
                    or index != len(sections) - 1
                    or any(category(char).startswith('C') for char in value)
                    or not all(_has_visible_text(label)
                               for model, roles in _ATTRIBUTION.findall(
                                   value.removeprefix('Generated by '))
                               for label in (model, *roles.split(', ')))):
                errors.append(FOOTER_ERROR)
        elif section.key == 'bugs discovered':
            items = _bug_items(section.content)
            matches = [_BUG.fullmatch(item) for item in (items or [])]
            if not matches or any(match is None for match in matches):
                errors.append(BUGS_ERROR)
            else:
                pointers.extend((int(match[1]), match[2]) for match in matches)
    return errors, pointers


def bug_issue_errors(pointers, records):
    errors = []
    for number, title in pointers:
        if number not in records:
            continue
        issue = records[number]
        if (issue is None or 'pull_request' in issue
                or issue.get('title') != title):
            errors.append(
                f'Bugs Discovered pointer `#{number}` must name an existing '
                'issue in this repository and copy its visible title exactly.')
    return errors
